name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  update-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@b4dbf08f349e421f15f15994d1f6f8c319e8f6b5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
