name: Release Drafter

on:
  workflow_run:
    workflows:
      - Publish Container Images
    types:
      - completed

permissions:
  contents: write
  pull-requests: read

jobs:
  update-draft:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@b4dbf08f349e421f15f15994d1f6f8c319e8f6b5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
